# Generated by Django 4.2 on 2024-10-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='password',
            field=models.CharField(default='default_password', max_length=30),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='username',
            field=models.CharField(default='default_username', max_length=150, unique=True),
        ),
    ]
