# Generated by Django 4.2 on 2024-10-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0007_flat_flatimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatimage',
            name='image',
            field=models.ImageField(upload_to='flat_images/%Y/%m/%d/'),
        ),
    ]
