# Generated by Django 4.2 on 2024-11-11 20:15

from django.db import migrations, models
import proapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0008_alter_flatimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='type_of_flat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flatimage',
            name='image',
            field=models.ImageField(upload_to=proapp.models.flat_image_upload_path),
        ),
    ]
