# Generated by Django 4.2 on 2024-11-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0009_flat_description_flat_type_of_flat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='buy_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='rent_amount',
            field=models.IntegerField(null=True),
        ),
    ]
