# Generated by Django 4.2 on 2024-11-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0011_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='payment_status_flat',
            field=models.IntegerField(default=1),
        ),
    ]
