# Generated by Django 4.2 on 2024-11-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0012_flat_payment_status_flat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('program_reg_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('approval_status', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('program_image', models.ImageField(blank=True, null=True, upload_to='program_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='proapp.userprofile')),
            ],
        ),
    ]
