# Generated by Django 4.2 on 2024-11-12 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0013_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_reg_fee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='program',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_image',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_reg_fees',
        ),
        migrations.RemoveField(
            model_name='program',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='program',
            name='registration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='proapp.userprofile'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_registration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program', to='proapp.programregistration'),
        ),
    ]
