# Generated by Django 4.2 on 2024-11-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0014_programregistration_remove_program_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_image',
            field=models.ImageField(blank=True, null=True, upload_to='program_images/'),
        ),
    ]
